services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 esp32cam_project.asgi:application
    volumes:
      - .:/app
    ports: 
      - "8000:8000"  # Проброс порта 8000 из контейнера на хост-машину
    depends_on:
      - redis
    environment:
      - DEBUG=1  # Переменная окружения для Django
      - REDIS_URL=redis://redis:6379/1
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
    # env_file:
    #   - .env
    networks:
      - webnet
      

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - webnet

  redis:
    image: redis:alpine
    networks:
      - webnet

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"  # MQTT-протокол
      - "9001:9001"  # WebSocket (опционально)
    networks:
      - webnet

networks:
  webnet: